language: android
jdk: oraclejdk8
android:
  components:
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra
licenses:
    - 'android-sdk-license-.+'
notifications:
  email: false
before_install:
 - chmod +x gradlew
